---
name: Getopt-Lucid
version: 0.18
author:
  - 'David A. Golden <dagolden@cpan.org>'
abstract: 'Clear, readable syntax for command line processing'
license: apache
resources:
  license: http://www.apache.org/licenses/LICENSE-2.0.txt
  repository: http://dagolden.googlecode.com/svn/
requires:
  Carp: 0
  Exception::Class: 1.23
  Exporter: 0
  Storable: 2.16
  perl: 5.006
build_requires:
  Data::Dumper: 0
  Exception::Class::TryCatch: 1.1
  Test::More: 0.62
provides:
  Getopt::Lucid:
    file: lib/Getopt/Lucid.pm
    version: 0.18
  Getopt::Lucid::Exception:
    file: lib/Getopt/Lucid/Exception.pm
    version: 0.18
  Getopt::Lucid::Spec:
    file: lib/Getopt/Lucid.pm
    version: 0
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
no_index:
  directory:
    - examples
    - inc
